# Production settings

from settings.common import *

DEBUG = False
DEBUG_SQL = False
TEMPLATE_DEBUG = DEBUG
SEND_BROKEN_LINK_EMAILS = True

SECRET_KEY = '%m14&o%qr^9*=i)!5010@%v)w65w5)awnpbar6*=#rvv&7fagl'

DATABASE_NAME = 'breakout'
DATABASE_USER = 'breakout'
DATABASE_PASSWORD = ''
DATABASE_HOST = ''
DATABASE_PORT = ''

# SESSION_COOKIE_SECURE = True

GOOGLE_MAPS_API_KEY = 'ABQIAAAAZ2jpq9DecEp8EYUNWHTHVxSaPikV0z6a0D2xh92lhEDLt_JARBTZKDBqz03yWPcBuNx4lc8kNMhaLA'

ANALYTICS_ID = 'UA-5053085-4'
